Switched to the more performant System.Threading.Lock on .NET 9.0+
jaredpar/complog pull request #163
Opened 2024-10-12 17:15 UTC by MarkCiliaVincenti

2024-10-13 17:17 UTC, jaredpar requested changes
Not sure if I want to go this direction. The existing use of locking is not a known source of performance issues with this tool or library (the bottlenecks are very much elsewhere). Further taking this change relies on my removing several TFMs that I actively support today.

2024-10-13 17:17 UTC, jaredpar commented on src/Basic.CompilerLog.UnitTests/Basic.CompilerLog.UnitTests.csproj
> +    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
Can't remove `net472` here as that is a TFM that I support and test.

2024-10-13 17:17 UTC, jaredpar commented on src/Basic.CompilerLog.Util/Basic.CompilerLog.Util.csproj
> -    <TargetFrameworks>net8.0;net9.0;net472;netstandard2.0</TargetFrameworks>
This is removing platforms that I actively support.

2024-10-13 17:26 UTC, MarkCiliaVincenti commented
> Not sure if I want to go this direction. The existing use of locking is not a known source of performance issues with this tool or library (the bottlenecks are very much elsewhere). Further taking this change relies on my removing several TFMs that I actively support today.

I can fix the issues so that the factory method is used instead, but not sure if you still want this.
https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock?tab=readme-ov-file#factory-method-if-targeting-frameworks-prior-to-net-50

2024-10-14 15:36 UTC, jaredpar commented
Thanks for the contribution but don't think I want to go in this direction. The performance around the limited locking here is not enough of a concern to introduce this disruptive of a change.

2024-10-14 15:36 UTC, closed without merging

2024-10-14 15:59 UTC, MarkCiliaVincenti commented
OK @jaredpar

2024-11-17 09:30 UTC, MarkCiliaVincenti commented
@jaredpar a new version of Backport.System.Threading.Lock has come out that acts as a source generator and basically dropping the DLL as a dependency. If this new development makes you reconsider, I will amend this PR accordingly.